### ISSUE TITLE
gernerics question 

### ISSUE THREAD

**Issue by HoseinRezaeeM** [farzadafi/cinema_101#16]
public  static <E extends Number> void f (E i){.....}
public  static  void f (Number i){.....}

Why we can't overload method? 
because Erasure 
compiler translate rawtype in runtime 
do you Agree???
@farzadafi 
@SinaAfzal
@sahargholami1992 
@samaboshagh 
@xaso21 
@AmirTghizde

**Comment by ShayanRahmdel** [comment]
maybe

**Comment by HoseinRezaeeM** [comment]
compiler translate rawtype in runtime and two method have same parameters so are not overload

**Comment by farzadafi** [comment]
Hi Hossein, excuse me for the latency in my answers
Yes, I agree that one reason why we can't overload methods with the same signature but different generic types is because of type erasure. During compilation, the compiler replaces all generic type parameters with their upper bounds or with the Object class if no bound is specified. This means that at runtime, both methods would have the same signature and would cause a compilation error. To avoid this, we can use different method names or different parameter types that are not erased in the same way.

**Comment by HoseinRezaeeM** [comment]
Thanks Mr.Afshar 
very good
